# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        miniature:
            quality: 75
            filters:
                thumbnail:
                    size: [500,500]
                    # pour choisir comment l'image est coupée (outbound prend du centre)
                    mode: outbound 
        scaleAccueil:
            quality: 75
            filters:
                scale:
                    dim: [1200,1200]
